# Generated by Django 5.0.6 on 2024-07-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_body_post_content_alter_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='NewsletterUser',
        ),
        migrations.RenameField(
            model_name='newsletteruser',
            old_name='date_subscribed',
            new_name='created',
        ),
    ]
